### ISSUE TITLE
no CA certificates found

### ISSUE THREAD

**Issue by hulk510** [4m-mazi/osekkai-chan#32]
![スクリーンショット 2024-01-04 17 57 36](https://github.com/4m-mazi/osekkai-chan/assets/33943897/0d3fbe8e-2e0e-4971-966c-4e06a5881074)

なんのエラーかわからないがデプロイすると実行できない。
https://github.com/4m-mazi/osekkai-chan/pull/25
での修正を行ったが変わらずエラーが出たままになっている。

**Comment by Mogyuchi** [comment]
なおらん

**Comment by hulk510** [comment]
かなし
